# The WORKSPACE file tells Bazel that this directory is a "workspace", which is like a project root.
# The content of this file specifies all the external dependencies Bazel needs to perform a build.

####################################
# ESModule imports (and TypeScript imports) can be absolute starting with the workspace name.
# The name of the workspace should match the npm package where we publish, so that these
# imports also make sense when referencing the published package.
workspace(
    name = "examples_vite",
    managed_directories = {"@npm": ["node_modules"]},
)

local_repository(
    name = "ubiquitous_tech_rules_vite",
    path = "../../../rules_vite",
)

# # VITE_COMMIT = "2790cd1964bf8a8c70c77ddc7ea32220ff000744"

# # VITE_SHA256 = "55f97743ec28e1b3ef24547d7f171a381cca46c8c296267bac32f77faec25075"

# # http_archive(
# #     name = "ubiquitous_tech_rules_vite",
# #     sha256 = VITE_SHA256,
# #     strip_prefix = "rules_vite-%s" % VITE_COMMIT,
# #     urls = ["https://github.com/ubiquitoustech/rules_vite/archive/%s.zip" % VITE_COMMIT],
# # )

# load("@ubiquitous_tech_rules_vite//vite:repositories.bzl", "rules_vite_dependencies")

# rules_vite_dependencies()
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "4501158976b9da216295ac65d872b1be51e3eeb805273e68c516d2eb36ae1fbb",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.4.1/rules_nodejs-4.4.1.tar.gz"],
)

# Check the bazel version and download npm dependencies
load("@build_bazel_rules_nodejs//:index.bzl", "node_repositories", "yarn_install")

node_repositories(
    node_version = "16.10.0",
)

# Setup the Node.js toolchain & install our npm dependencies into @npm
yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
